package ca.markhauser.chess;

public enum MoveResult {
	MOVED, ILLEGALMOVEFORPIECE, WRONGCOLOUR, UNDEFINED, SOURCEOUTOFRANGE, DESTINATIONOUTOFRANGE, NOPIECEONSOURCE, SAMESOURCEANDDESTINATION, ANOTHERPIECEINPATH,
}
